language: ruby
rvm:
  - 2.0.0
  - 2.1.2
  - 2.1.5
  - 2.2.0
gemfile:
  - gemfiles/3.2.gemfile
  - gemfiles/4.0.gemfile
  - gemfiles/4.1.gemfile
  - gemfiles/4.2.gemfile
install:
  - "travis_retry bundle install"
